mybatis:
  type-aliases-package:com.ssm.pojo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.156:3306/egenie
    username: root
    password: ejl13579

server:
  port: 8090
  session:
      timeout: 120
